name: collabsync
services:
  file-service-db:
    image: postgres:latest
    container_name: file-service-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - file-service-db-data:/var/lib/postgresql/data
    env_file: .env

volumes:
  file-service-db-data:
    driver: local
    driver_opts:
      type: none
      device: ./backup/file-service-postgresql-data
      o: bind

networks:
  default:
    name: collabsync_default
    driver: bridge
