name: auth-service
services:
  auth-service-db:
    image: mongo:latest
    container_name: auth-service-db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - auth-service-db-data:/data/db

  auth-service:
    build:
      context: ../services/nodejs/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "3000:3000"
    depends_on:
      - auth-service-db
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@auth-service-db:27017/${MONGO_DBNAME}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - KAFKA_BROKER=${KAFKA_BROKER}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
    env_file:
      - ../services/nodejs/auth-service/.env

volumes:
  auth-service-db-data:
    driver: local
    driver_opts:
      type: none
      device: ./backup/auth-service-db-data
      o: bind

networks:
  default:
    name: collabsync_default
    driver: bridge
