name: collabsync
services:
  file-service-db:
    image: postgres:latest
    container_name: file-service-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - file-service-db-data:/var/lib/postgresql/data
    networks:
      - collabsync-network
    env_file: .env
