name: collabsync
services:
  redis:
    image: redis:latest
    container_name: redis-service
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:
      [
        "redis-server",
        "--save 20 1",
        "--loglevel notice",
        "--requirepass",
        "${REDIS_PASSWORD}",
      ]
    volumes:
      - redis-data:/data
    env_file: .env
    networks:
      - collabsync-network
