name: collabsync

services:
  ffmpeg:
    image: jrottenberg/ffmpeg:latest
    container_name: ffmpeg
    environment:
      - FFMPEG_LOG_LEVEL=info
    volumes:
      - ${FFMPEG_FOLDER_PATH}:/data
    env_file: .env

networks:
  collabsync_default:
    name: collabsync_default
    driver: bridge
